# Generated by Django 4.2.2 on 2023-07-05 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_v2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolistmodels',
            old_name='tasks',
            new_name='old_tasks',
        ),
    ]
