# Generated by Django 4.2.2 on 2023-07-05 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_v2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusmodel',
            options={'verbose_name': 'Статусы', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterModelOptions(
            name='tasksmodel',
            options={'verbose_name': 'Типы задач', 'verbose_name_plural': 'Типы задач'},
        ),
        migrations.AlterModelOptions(
            name='todolistmodels',
            options={'verbose_name': 'Список задач', 'verbose_name_plural': 'Список задач'},
        ),
        migrations.AlterModelTable(
            name='statusmodel',
            table='StatusModel',
        ),
        migrations.AlterModelTable(
            name='tasksmodel',
            table='TasksModel',
        ),
        migrations.AlterModelTable(
            name='todolistmodels',
            table='ToDoList',
        ),
    ]
