# Generated by Django 4.2.2 on 2023-07-05 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_v2', '0002_alter_statusmodel_options_alter_tasksmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistmodels',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='to_do_list_v2.tasksmodel', verbose_name='Типы задач'),
        ),
    ]
