# Generated by Django 4.2.2 on 2023-07-05 19:37

from django.db import migrations


def transfer_tags(apps, schema_editor):
    ToDoList = apps.get_model('to_do_list_v2.ToDoListModels')
    for todolist in ToDoList.objects.all():
        todolist.tasks.add(todolist.old_tasks)


def rollback_transfer(apps, schema_editor):
    ToDoList = apps.get_model('to_do_list_v2.ToDoListModels')
    for data in ToDoList.objects.all():
        data.old_tasks.add(data.tasks)


class Migration(migrations.Migration):
    dependencies = [
        ('to_do_list_v2', '0003_todolistmodels_tasks_alter_todolistmodels_old_tasks'),
    ]

    operations = [
        migrations.RunPython(transfer_tags, rollback_transfer)
    ]
