# Generated by Django 4.2.2 on 2023-07-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_v2', '0005_remove_todolistmodels_old_tasks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmodel',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='tasksmodel',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Наименование'),
        ),
    ]
