# Generated by Django 4.2.2 on 2023-07-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_v2', '0006_alter_statusmodel_title_alter_tasksmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('description', models.TextField(max_length=300, verbose_name='Название')),
                ('create_date', models.DateField(verbose_name='Дата начала')),
                ('update_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
            ],
            options={
                'verbose_name': 'Список проектов',
                'verbose_name_plural': 'Список проектов',
                'db_table': 'Project',
            },
        ),
    ]
