# Generated by Django 4.2.2 on 2023-07-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_v2', '0008_rename_update_date_projectmodels_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodels',
            name='end_date',
            field=models.DateField(blank=True, default=None, verbose_name='Дата окончания'),
        ),
    ]
