# Generated by Django 4.2.2 on 2023-07-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_v2', '0009_alter_projectmodels_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodels',
            name='end_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='projectmodels',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата начала'),
        ),
    ]
