# Generated by Django 4.2.2 on 2023-07-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list_v2', '0013_projectmodels_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodels',
            options={'permissions': [('change_author_projectmodels', 'Изменить авторов проекта')], 'verbose_name': 'Список проектов', 'verbose_name_plural': 'Список проектов'},
        ),
    ]
